name: "❓ Question"
description: Ask a question or get help
title: "[QUESTION]: "
labels:
  - question
body:
  - type: textarea
    id: question
    attributes:
      label: Ask your question
      description: We'll try to help as best as we can!
    validations:
      required: true
